//
// Created by ishik on 31/03/2021.
//

#ifndef SOFTWARE_1_LIBRARY_H
#define SOFTWARE_1_LIBRARY_H
/* Declaration */
char STORED_RESULTS[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char temperory[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char RANDOM_ARRAY[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char PRESENT_ARTIST[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char PRECEDING_ARTIST[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char SONGS[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char TIME_OF_SONGS[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char ARTIST[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char SONG_TIME[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
char ARTISTE[MAXIMUM_LINES][MAXIMUM_COMPONENTS];
void ENTERED_BY_USER(char STORED_RESULTS[MAXIMUM_LINES][MAXIMUM_COMPONENTS]);
void READ_SONGS_FROM_FILE(FILE *input, char STORED_RESULTS[MAXIMUM_LINES][MAXIMUM_COMPONENTS]) ;
void SORT_RESULTS(char STORED_RESULTS[MAXIMUM_LINES][MAXIMUM_COMPONENTS]);
void PRINT_SORT_RESULTS(char STORED_RESULTS[MAXIMUM_LINES][MAXIMUM_COMPONENTS]);
void RANDOM_RESULTS(char STORED_RESULTS[][MAXIMUM_COMPONENTS]);
void PRINT_RANDOM_RESULTS(char STORED_RESULTS[][MAXIMUM_COMPONENTS]);
int number_of_songs;
int ENTIRE_PLAYLIST_TIME; //total duration of the playlist is initialised to 0 in the beginning
int counting ;
int i;
int j;
int minitue;
int seconds;
char *token;
#endif //SOFTWARE_1_LIBRARY_H
